### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bubobih** [unhaten/flightradar-extention#1]
Hello extension not working, i move to extension folder but chrome and edge autoremove it

**Comment by unhaten** [comment]
i am going to fix it soon, probably know where is the problem

**Comment by bubobih** [comment]
i hope u will do it soon. :) and please tag me when u fix it if u can here :)

**Comment by unhaten** [comment]
> i hope u will do it soon. :) and please tag me when u fix it if u can here :)

you can try to use it now
